# Simple Linear Regression - Example: Cancer Experiment 


```{r, include=FALSE}
# set global chunk options...  
#  this changes the defaults so you don't have to repeat yourself
knitr::opts_chunk$set(comment     = NA,
                      cache       = TRUE,
                      echo        = TRUE, 
                      warning     = FALSE, 
                      message     = FALSE,
                      out.width   = "75%")
```



## Background

### Required Packages 

```{r, comment=FALSE, message=FALSE}
library(tidyverse)    # Loads several very helpful 'tidy' packages
library(haven)        # Read in SPSS datasets
library(psych)        # Lots of nice tid-bits
library(GGally)       # Extension to 'ggplot2' (ggpairs)
library(furniture)    # tables
library(apaSupp)      # APA 7th ed tables
library(emmeans)
library(effects)
```

```{r}
emmeans::emm_options(opt.digits = FALSE)  # revert to optimal digits
```



### Example Dataset - Cancer Experiment 

The `Cancer` dataset:


```{r}
cancer_raw <- haven::read_spss("https://raw.githubusercontent.com/CEHS-research/eBook_ANOVA/master/data/Cancer.sav")

tibble::glimpse(cancer_raw)
```

```{r}
cancer_clean <- cancer_raw %>% 
  dplyr::rename_all(tolower) %>% 
  dplyr::mutate(id = factor(id)) %>% 
  dplyr::mutate(trt = factor(trt,
                             labels = c("Placebo", 
                                        "Aloe Juice"))) %>% 
  dplyr::mutate(stage = factor(stage))

tibble::glimpse(cancer_clean)
```



```{r}
psych::headTail(cancer_clean) %>% 
  flextable::flextable() %>% 
  apaSupp::theme_apa(caption = "Sample of Cancer Dataset")
```




## Exploratory Data Analysis: i.e. the eyeball method

### Scatterplot

Always plot your data first!

```{r}
cancer_clean %>% 
  ggplot(aes(x = age,
             y = weighin)) +
  geom_point() +
  geom_smooth(aes(color = "Linear"), method = "lm",    se = TRUE) +  
  geom_smooth(aes(color = "Loess"),  method = "loess", se = FALSE) +     
  theme_bw()
```


## Regression Model

### Fit the Model

```{r}
fit_lm <- lm(weighin ~ age,
             data = cancer_clean)
```


### Parameter Estimates

```{r}
summary(fit_lm)
```



### Prediction Equation

```{r}
coef(fit_lm)
```



$$
\hat{weight} = 220.69 - 0.71 \times (age)
$$


### Estimated Marginal Means

```{r}
fit_lm %>% 
  emmeans::emmeans(~ age)
```

```{r}
fit_lm %>% 
  emmeans::emmeans(~ age,
                   at = list(age = c(30, 60, 90))) 
```


```{r}
fit_lm %>% 
  emmeans::emmeans(~ age,
                   at = list(age = seq(from = 30, to = 90, by = 10)))
```


```{r}
fit_lm %>% 
  effects::Effect(focal.predictors = c("age"))
```


```{r}
fit_lm %>% 
  effects::Effect(focal.predictors = c("age"),
                  xlevels = list(age = seq(from = 30, to = 90, by = 1))) %>% 
  data.frame() 
```




```{r, fig.cap = "Weight Regressed on Age"}
fit_lm %>% 
  effects::Effect(focal.predictors = c("age"),
                  xlevels = list(age = seq(from = 30, to = 90, by = 1))) %>% 
  data.frame() %>% 
  ggplot(aes(x = age,
             y = fit)) +
  geom_ribbon(aes(ymin = fit - se,
                  ymax = fit + se),
              alpha = .2) +
  geom_line() +
  theme_bw() +
  labs(x = "Age, years",
       y = "Estimated Marginal Mean\nWeight, pounds")
```



